# Generated by Django 4.2.7 on 2023-11-21 10:11

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('restaurant_id', models.CharField(max_length=255)),
                ('table_id', models.CharField(max_length=255)),
                ('reserved_status', models.SmallIntegerField()),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255)),
                ('table', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_and_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], max_length=255)),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='PAID', max_length=255)),
                ('waiter_id', models.IntegerField()),
                ('payment_time', models.DateTimeField()),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'billing_history',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('restaurant_id', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=255)),
                ('menu_id', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('restaurant_id', models.IntegerField()),
                ('access_token', models.SmallIntegerField()),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('menu_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('restaurant_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('available', models.CharField(max_length=255)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('restaurant_id', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('table_no', models.CharField(max_length=255)),
                ('food_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField()),
                ('user_id', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
                ('menu_id', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=255)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='RestaurantWaiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=255)),
                ('waiter_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('phone', models.BigIntegerField()),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.BigIntegerField()),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='UserOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('menu_id', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('customer_id', models.CharField(max_length=255)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user_orders_history',
            },
        ),
        migrations.CreateModel(
            name='WaiterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=225)),
                ('order_id', models.CharField(max_length=255)),
                ('waiter_id', models.CharField(max_length=255)),
                ('table_no', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'waiter_history',
            },
        ),
        migrations.CreateModel(
            name='TableNo',
            fields=[
                ('table_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('VACANT', 'VACANT'), ('OCCUPIED', 'OCCUPIED')], max_length=255)),
                ('restaurant_id', models.IntegerField()),
                ('is_removed', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manager')),
            ],
            options={
                'verbose_name': 'table_no',
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('is_removed', models.BooleanField(default=False)),
                ('table_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tableno')),
            ],
            options={
                'verbose_name': 'restaurant_table',
                'verbose_name_plural': 'restaurant_tables',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('thumbnail', models.CharField(max_length=255)),
                ('song_name', models.CharField(max_length=255)),
                ('duration', models.TimeField()),
                ('artist', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('set_waiting_time', models.TimeField()),
                ('request_status', models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('AWAITING_CONFIRMATION', 'AWAITING_CONFIRMATION'), ('SCHEDULED', 'SCHEDULED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DELAYED', 'DELAYED')], max_length=255)),
                ('restaurant_id', models.IntegerField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.manager')),
            ],
            options={
                'verbose_name': 'dj',
            },
        ),
        migrations.CreateModel(
            name='Universal',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date_column', models.DateField()),
                ('resId', models.CharField(max_length=255)),
                ('is_removed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'universal',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
