# Generated by Django 4.2.7 on 2023-11-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universal',
            name='date_column',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universal',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universal',
            name='resId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universal',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
